[entryPoints]
  [entryPoints.http]
    address = ":8080"
  [entryPoints.traefik]
    address = ":8081"

[api]
  dashboard = true
  insecure = true

[providers]
  [providers.file]
    directory = "/etc/traefik/services"